### ISSUE TITLE
INSTALL file mentioned yet missing.

### ISSUE THREAD

**Issue by pvphaneuf** [agordon/libgtextutils#5]
INSTALL file mentioned in README yet missing.

INSTALL is included in the .gitignore file and may therefore be committed to the repo.

**Comment by agordon** [comment]
Hello @pvphaneuf,

The INSTALL file is automatically added by gnu autotools when you run `./reconf` - therfor it is not included in the git repository (and also mentioned in `.gitignore` - because it should not be in the git repo).
Alternatively, If you download the tarball (instead of using git) - the INSTALL file is included in the tarball.

regards,
 - assaf
